version: "3"

services:
  db:
    image: postgres:11.7
    container_name: fastapi-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memo
  app:
    image: python:3.8.2-slim
    container_name: fastapi-app
    volumes:
      - ./src:/usr/src
    environment:
      - PYTHONPATH=${PYTHONPATH}:/usr/src
    tty: true
